name: (dry-run) Auto deploy the Angular App to GitHub Pages

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo yarn onboard
          yarn
          sudo yarn build:gh-pages --name="wataruoguchi" --email="wataru.oguchi.0to1@gmail.com" --dry-run
